SET (private_mod_path "${CMAKE_SOURCE_DIR}/cmake")
LIST (APPEND CMAKE_MODULE_PATH "${private_mod_path}")
SET (_result)
INCLUDE(Shlomif_Common OPTIONAL RESULT_VARIABLE _result)

IF ("${_result}" STREQUAL "NOTFOUND")
    MESSAGE (WARNING "Could not find Shlomif_Common.cmake - you can find it here: https://github.com/shlomif/shlomif-cmake-modules ; trying to download it for you.")
    FILE (DOWNLOAD "https://raw.githubusercontent.com/shlomif/shlomif-cmake-modules/master/shlomif-cmake-modules/Shlomif_Common.cmake" "${private_mod_path}/Shlomif_Common.cmake")
    INCLUDE(Shlomif_Common)
ENDIF ()
